### ISSUE TITLE
In the Dedication, should the cite be small caps?

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/solomon-northup_twelve-years-a-slave#5]
"Key to Uncle Tom's Cabin" shows are regular text, shouldn't it be small-caps?

**Comment by drgrigg** [comment]
shows AS regular text. Can't type these days...

**Comment by vr8hub** [comment]
Well, it's not _really_ regular text, it's italicized italics. The cite itself is italics (see the _p. 174_) which is what blockquote cites normally are (see core.css), but since the book tag italicizes the book name, then an italic inside an italic ends up looking normal. I have these all over _Decline and Fall_. I can override it if you wish, but that's all core behavior.

**Comment by drgrigg** [comment]
I understand about the italics within italics, but it looks a bit odd. What about small-caps? That's what the epigraph does with the citation.

**Comment by vr8hub** [comment]
Sure, that quote is epigraph'ish. Changed and pushed.
